In [1]:
from sqlalchemy import create_engine
import pandas as pd

In [2]:
# from config import username, password, dbname
# url = f'postgresql://{username}:{password}@localhost:5432/{dbname}'
# # Create an engine object.
# engine = create_engine(url, echo=True)

In [5]:
engine = create_engine('postgresql://postgres:postgres@localhost:5432/postgres')

In [6]:
data_df = pd.read_sql('select * from ccf', engine.connect())

In [8]:
data_df

,user_,card,year_,month_,day_,time_,amount,use_chip,merchant_name,merchant_city,merchant_state,zip,mcc,errors,is_fraud
0,0,0,2002,9,1,06:21:00,$134.09,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,None,No
1,0,0,2002,9,1,06:42:00,$38.48,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,None,No
2,0,0,2002,9,2,06:22:00,$120.34,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,None,No
3,0,0,2002,9,2,17:45:00,$128.95,Swipe Transaction,3414527459579106770,Monterey Park,CA,91754.0,5651,None,No
4,0,0,2002,9,3,06:23:00,$104.71,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,None,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24386895,1999,1,2020,2,27,22:23:00,$-54.00,Chip Transaction,-5162038175624867091,Merrimack,NH,3054.0,5541,None,No
24386896,1999,1,2020,2,27,22:24:00,$54.00,Chip Transaction,-5162038175624867091,Merrimack,NH,3054.0,5541,None,No
24386897,1999,1,2020,2,28,07:43:00,$59.15,Chip Transaction,2500998799892805156,Merrimack,NH,3054.0,4121,None,No
24386898,1999,1,2020,2,28,20:10:00,$43.12,Chip Transaction,2500998799892805156,Merrimack,NH,3054.0,4121,None,No
24386899,1999,1,2020,2,28,23:10:00,$45.13,Chip Transaction,4751695835751691036,Merrimack,NH,3054.0,5814,None,No